spring:
  application:
    name: eureka-client
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xjlonly/config-repo-demo/
#    consul:
#      host: localhost
#      port: 8500

server:
  port: 2001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/

encrypt:
  key: dispose123
  key-store:
    location: classpath:/eurekaclient.keystore
    alias: eurekaclient
    password: 123456
    secret: 123456

