spring:
  application:
    name: api-gateway
server:
  port: 1101

eureka:
  client:
    service-url:
      defaultZone: http://139.199.117.109:1001/eureka

  instance:
    prefer-ip-address: true
    ip-address: 139.199.117.109
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}

zuul:
  routes:
    test-client:
      path: /client/**
      service-id: eureka-testclient
