---
server:
  port: 1001
spring:
  profiles: server01
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
    #高可用注册中心时必须开启
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://139.199.117.109:1002/eureka/
---

server:
  port: 1002

spring:
  profiles: server02
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
    #高可用注册中心时必须开启
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://139.199.117.109:1001/eureka/