server:
  port: 2101


spring:
  application:
    name: eureka-consumer

eureka:
  client:
    service-url:
      defaultZone: http://139.199.117.109:1001/eureka/

feign:
  hystrix:
    enabled: true

management:
  security:
    enabled: false

swagger:
  base-package:  com.example.eureka

