server:
  port: 2101


spring:
  zipkin:
    base-url: http://localhost:3001
  application:
    name: eureka-consumer
  rabbitmq:
    host: 139.199.117.109
    port: 5672
    username: jtest
    password: 123456
    virtual-host: test


  cloud:
    stream:
      bindings:
        input:
          group: eureka-consumer
          # 消费者分组
          destination: test-message
          #开启消费者分区功能
          consumer:
            partitioned: true
        output:
#          生产者分组
          destination: test-message
          producer:
            partitionKeyExpression: payload
            partitionCount: 2
      instance-count: 2
      instance-index: 0
eureka:
  client:
    service-url:
      defaultZone: http://139.199.117.109:1001/eureka/

feign:
  hystrix:
    enabled: true

management:
  security:
    enabled: false

swagger:
  base-package:  com.example.eureka

